src/Entity/HistoStories.php
<?php

namespace App\Entity;

use App\Repository\HistoStoriesRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: HistoStoriesRepository::class)]
class HistoStories
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: "integer")]
    private $id;

    #[ORM\Column(length: 50)]
    private ?string $nom_sortie = null;

    #[ORM\Column(length: 255)]
    private ?string $adresse_sortie = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_heure_debut = null;

    #[ORM\Column]
    private ?int $duree = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_limite_inscription = null;

    #[ORM\Column]
    private ?int $nb_inscriptions_max = null;

    #[ORM\Column(length: 255)]
    private ?string $infos_sortie = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $motif_annulation = null;

    #[ORM\Column(length: 10)]
    private ?string $libelle_etat = null;

    #[ORM\Column(length: 255)]
    private ?string $nom_organisateur = null;

    #[ORM\Column(length: 50)]
    private ?string $prenom_organisateur = null;

    #[ORM\Column(length: 50)]
    private ?string $tel_organisateur = null;

    #[ORM\Column(length: 50)]
    private ?string $email_organisateur = null;

    #[ORM\Column(length: 50)]
    private ?string $pseudo_organisateur = null;

    #[ORM\Column(length: 50)]
    private ?string $site_organisateur = null;

    #[ORM\Column(type: Types::JSON)]
    private array $participants = [];

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomSortie(): ?string
    {
        return $this->nom_sortie;
    }

    public function setNomSortie(string $nom_sortie): static
    {
        $this->nom_sortie = $nom_sortie;

        return $this;
    }

    public function getAdresseSortie(): ?string
    {
        return $this->adresse_sortie;
    }

    public function setAdresseSortie(string $adresse_sortie): static
    {
        $this->adresse_sortie = $adresse_sortie;

        return $this;
    }

    public function getDateHeureDebut(): ?\DateTimeInterface
    {
        return $this->date_heure_debut;
    }

    public function setDateHeureDebut(\DateTimeInterface $date_heure_debut): static
    {
        $this->date_heure_debut = $date_heure_debut;

        return $this;
    }

    public function getDuree(): ?int
    {
        return $this->duree;
    }

    public function setDuree(int $duree): static
    {
        $this->duree = $duree;

        return $this;
    }

    public function getDateLimiteInscription(): ?\DateTimeInterface
    {
        return $this->date_limite_inscription;
    }

    public function setDateLimiteInscription(\DateTimeInterface $date_limite_inscription): static
    {
        $this->date_limite_inscription = $date_limite_inscription;

        return $this;
    }

    public function getNbInscriptionsMax(): ?int
    {
        return $this->nb_inscriptions_max;
    }

    public function setNbInscriptionsMax(int $nb_inscriptions_max): static
    {
        $this->nb_inscriptions_max = $nb_inscriptions_max;

        return $this;
    }

    public function getInfosSortie(): ?string
    {
        return $this->infos_sortie;
    }

    public function setInfosSortie(string $infos_sortie): static
    {
        $this->infos_sortie = $infos_sortie;

        return $this;
    }

    public function getMotifAnnulation(): ?string
    {
        return $this->motif_annulation;
    }

    public function setMotifAnnulation(string $motif_annulation): static
    {
        $this->motif_annulation = $motif_annulation;

        return $this;
    }

    public function getLibelleEtat(): ?string
    {
        return $this->libelle_etat;
    }

    public function setLibelleEtat(string $libelle_etat): static
    {
        $this->libelle_etat = $libelle_etat;

        return $this;
    }

    public function getNomOrganisateur(): ?string
    {
        return $this->nom_organisateur;
    }

    public function setNomOrganisateur(string $nom_organisateur): static
    {
        $this->nom_organisateur = $nom_organisateur;

        return $this;
    }

    public function getPrenomOrganisateur(): ?string
    {
        return $this->prenom_organisateur;
    }

    public function setPrenomOrganisateur(string $prenom_organisateur): static
    {
        $this->prenom_organisateur = $prenom_organisateur;

        return $this;
    }

    public function getTelOrganisateur(): ?string
    {
        return $this->tel_organisateur;
    }

    public function setTelOrganisateur(string $tel_organisateur): static
    {
        $this->tel_organisateur = $tel_organisateur;

        return $this;
    }

    public function getEmailOrganisateur(): ?string
    {
        return $this->email_organisateur;
    }

    public function setEmailOrganisateur(string $email_organisateur): static
    {
        $this->email_organisateur = $email_organisateur;

        return $this;
    }

    public function getPseudoOrganisateur(): ?string
    {
        return $this->pseudo_organisateur;
    }

    public function setPseudoOrganisateur(string $pseudo_organisateur): static
    {
        $this->pseudo_organisateur = $pseudo_organisateur;

        return $this;
    }

    public function getSiteOrganisateur(): ?string
    {
        return $this->site_organisateur;
    }

    public function setSiteOrganisateur(string $site_organisateur): static
    {
        $this->site_organisateur = $site_organisateur;

        return $this;
    }

    public function getParticipants(): array
    {
        return $this->participants;
    }

    public function setParticipants(array $participants): static
    {
        $this->participants = $participants;

        return $this;
    }
}

src/Controller/MainController.php
<?php



namespace App\Controller;



use App\Entity\User;

use App\Form\FiltreSortieType;
use App\Repository\SiteRepository;
use App\Repository\SortieRepository;
use App\service\MainService;
use App\utils\EtatEnum;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;



class MainController extends AbstractController

{
    private $mainService;

    public function __construct(MainService $mainService)
    {
        $this->mainService = $mainService;
    }

    #[Route('/home', name: 'app_home')]
    public function home(
        SiteRepository $siteRepository,
        SortieRepository $sortieRepository,
        Request $request,
        EntityManagerInterface $entityManager
    ): Response {
        $sortiesList = $sortieRepository->findAll();
        $today = new \DateTime('now', new \DateTimeZone('Europe/Paris'));
        foreach ($sortiesList as $sortie) {
        if ($sortie->getDateDebut() !== null &&
            $sortie->getDateDebut()->format('Y-m-d') == $today->format('Y-m-d')) {
        $sortie->setEtat(EtatEnum::EN_COURS);
        $entityManager->persist($sortie);
        $entityManager->flush();
         }
        elseif($sortie->getDateDebut() !== null &&
            $sortie->getDateDebut()->format('Y-m-d') < $today->format('Y-m-d')) {
            $sortie->setEtat(EtatEnum::PASSEE);
            $entityManager->persist($sortie);
            $entityManager->flush();
        }
        elseif($sortie->getDateCloture() !== null &&
            $sortie->getDateCloture()->format('Y-m-d') <= $today->format('Y-m-d') &&
            $sortie->getEtat() == EtatEnum::OUVERTE
        ) {
            $sortie->setEtat(EtatEnum::CLOTUREE);
            $entityManager->persist($sortie);
            $entityManager->flush();
        }
        elseif ($sortie->getDateDebut() !== null &&
                $sortie->getDateDebut()->diff($today)->m >= 1) {
               $this->mainService->updateSortieEtat($sortie,$today);
       }

        }

        $user = $this->getUser();
        if (!$user instanceof User) {
            return $this->redirectToRoute('app_login');
        }
        $sites = $siteRepository->findAll();
        $userSite = $user->getSite();

        $filtreForm = $this->createForm(FiltreSortieType::class);
        $filtreForm->handleRequest($request);

        $sorties = $sortieRepository->findAll();

        return $this->render('main/index.html.twig', [
            'sites' => $sites,
            'sorties' => $sorties,
            'filtreForm' => $filtreForm->createView(),
            'userSite' => $userSite,
        ]);
    }

}

templates/main/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	{{ parent() }}
	| Home
{% endblock %}

{% block body %}
	{{ parent() }}
	<script src="{{ asset('js/filter.js') }}"></script>
	<div>
		{% for message in app.flashes('success') %}
			<div class="alert alert-success">
				{{ message }}
			</div>
		{% endfor %}
	</div>
	<div class="video-container">
		<video style="width: 100%" loop autoplay muted>
			<source src="{{ asset('movie/party.mp4#t=7') }}" type="video/mp4">
		</video>
	</div>

	<div>
		{{ form_start(filtreForm) }}
		<div class="row justify-content-center flex-equal-height">
			<div class="col-md-auto mx-4 mt-2">
				<h2 class="mb-3" style= "color: #7B8997;">Filtrer les sorties</h2>
				<!-- Barre de recherche -->
				<div class="form-outline mb-2">
					<input type="search" id="search" class="form-control" placeholder="Rechercher une sortie par mot clé"/>
				</div>
				<!-- Choisir un statut -->

				<div class="mb-2">

					<select class="form-select form-select-sm" aria-label=".form-select-sm example" name="etat">

						<option selected>Selectionner un statut</option>

						<option value="Ouverte">Ouverte</option>

						<option value="Créée">Créée</option>

						<option value="Annulée">Annulée</option>

						<option value="Passée">Passée</option>

						<option value="En Cours">En Cours</option>

					</select>

				</div>
				<!-- Choisir un site -->
				<div class="mb-2">
					<select class="form-select form-select-sm" aria-label=".form-select-sm example" name="site">
						<option selected>Selectionner le site</option>
						{% for site in sites %}
							<option value="{{ site.nom }}">{{ site.nom }}</option>
						{% endfor %}
					</select>
				</div>
			</div>

			<div class="col-md-auto mx-4 mt-5">
				<!-- Date de début -->
				<div class="form-outline mb-2">
					<label for="dateDebut" class="text-white">Date de début</label>
					<input type="date" class="form-control" id="dateDebut" name="dateDebut"/>
				</div>
				<!-- Date de fin -->
				<div class="form-outline mb-2">
					<label for="dateFin" class="text-white">Date de fin</label>
					<input type="date" class="form-control" id="dateFin" name="dateFin"/>
				</div>
			</div>
			<!-- Checkbox -->
			<div class="col-md-auto mx-4 mt-5">
				<div class="form-check">
					<input class="form-check-input" type="checkbox" value="{{ app.user.id }}" id="flexCheckDefault" name="organisateur">
					<label class="form-check-label text-white" for="flexCheckDefault">Sortie dont je suis l'organisateur/trice</label>
				</div>
				<div class="form-check">
					<input class="form-check-input" type="checkbox" value="{{ app.user.id }}" id="flexCheckChecked" name="inscrit">
					<label class="form-check-label text-white" for="flexCheckChecked">Sortie auxquelles je suis inscrit/e</label>
				</div>
				<div class="form-check">
					<input class="form-check-input" type="checkbox" value="" id="flexCheckDefault" name="nonInscrit">
					<label class="form-check-label text-white" for="flexCheckDefault">Sortie auxquelles je ne suis pas inscrit/e</label>
				</div>
				<div class="form-check">
					<input class="form-check-input" type="checkbox" value="" id="flexCheckChecked" name="passee">
					<label class="form-check-label text-white" for="flexCheckChecked">Sortie passées</label>
				</div>
			</div>
		</div>

		<div class="row justify-content-center mt-2">
			<!-- Boutons -->
			<div class="col-md-auto mt-5">
				<button type="reset" class="btn text-white" style="background-color:#214264; border-radius: 20px;"><a href="{{ path('app_home') }}" class="text-white" style="text-decoration: none">Réinitialiser</a></button>
			</div>
		</div>
		{{ form_end(filtreForm) }}
	</div>

		<span hidden id="userSite">{{ app.user.site ? app.user.site.nom : 'null' }}</span>

	<!-- Tableau des sorties -->
	<div class="mt-4 container">
		<h2 style="mb-3; color: #7B8997;">Liste des sorties</h2>
		{% if app.user is not null and 'ROLE_USER' in app.user.roles and app.user.actif %}
			<div class="text-end mb-3">
				<a href="{{ path('app_sortie_creer') }}" class="btn" style="background-color:#a1b1c3; outline: none;">Créer une sortie</a>
			</div>
		{% endif %}
		<table class="table table-striped table-over text-white">
			<thead class="table-dark">
			<tr>
				<th scope="col">#</th>
				<th scope="col">Nom de la sortie</th>
				<th scope="col">Date de la sortie</th>
				<th scope="col">Cloture</th>
				<th scope="col">inscrits/places</th>
				<th scope="col">Etat</th>
				<th scope="col">Inscrit</th>
				<th scope="col">Organisateur</th>
				<th scope="col">Site</th>
				<th scope="col">Actions</th>
			</tr>
			</thead>
			<tbody>
			{%  for sortie in sorties %}
				<tr class="{{ loop.index is odd ? 'bg-light-gray' : 'bg-light-green' }}">
					<th scope="row">{{ loop.index }}</th>
					<td>{{ sortie.nom }}</td>
					<td>{{ sortie.dateDebut | date('d/m/Y')}} à </td>
					<td>{{ sortie.dateCloture | date('d/m/Y')}}</td>
					<td>{{ sortie.usersInscrits|length }}/{{ sortie.nbInscriptionsMax }}</td>
					<td>{{ sortie.etat }}</td>
					<td>
						{%  set inscrit = false %}
						{%  for u in sortie.usersInscrits %}
							{% if u== app.user%}
								{%  set inscrit = true %}
							{% endif %}
						{% endfor %}

						{% if inscrit %}
							X
						{% endif %}


					</td>
					<td>
						<a href="{{ path('app_user_afficher',{id:sortie.auteur.id}) }}" class="text-decoration-none" style="color: #011F39; font-weight: bold">
							{{ sortie.auteur.prenom |capitalize }} {{ sortie.auteur.nom [:1] }}</a>
					</td>
					<td>{{ sortie.auteur.site.nom }}</td>

					<td>


						{% if sortie.auteur == app.user or 'ROLE_ADMIN' in app.user.roles %}
							{% if sortie.etat == 'Créée' and 'ROLE_USER' in app.user.roles  %}
								<a href="{{ path('app_sortie_modifier',{id:sortie.id}) }}">
									<button class="btn me-3" style="background-color:#F96321">Modifier</button>
								</a>
								<a href="{{ path('app_sortie_publication',{id:sortie.id}) }}">
									<button class="btn" style="background-color:#2CB451">Publier</button>
								</a>
							{% elseif sortie.etat != 'Créée'%}
								<a href="{{ path('app_sortie_afficher',{id:sortie.id}) }}">
									<button class="btn me-3" style="background-color:#ffffff">Afficher</button>
								</a>
							{% if sortie.etat != 'Annulée' and sortie.etat != 'En Cours'  %}
								<a href="{{ path('app_sortie_annuler',{id:sortie.id}) }}">
									<button class="btn" style="background-color:#FE0200">Annuler</button>
								</a>
							{% endif %}

							{% endif %}

						{% elseif sortie.auteur != app.user %}
							<a href="{{ path('app_sortie_afficher',{id:sortie.id}) }}">
								<button class="btn me-3" style="background-color:#ffffff">Afficher</button>
							</a>


							{% if inscrit  %}

								{%  if  'now'| date('d/m/y H:i')  <  sortie.dateDebut | date('d/m/Y H:i') or not 'now'| date('d/m/y')  >  sortie.dateCloture | date('d/m/Y') %}

									<a href="{{ path('app_sortie_desister',{id:sortie.id}) }}">
										<button class="btn btn-danger">Se désister</button>
									</a>
								{% endif %}

							{% elseif sortie.etat=='Ouverte' and sortie.usersInscrits|length <  sortie.nbInscriptionsMax and 'now'| date('d/m/y')  <=  (sortie.dateCloture | date('d/m/Y')) and 'ROLE_USER' in app.user.roles and app.user.actif %}
								<a href="{{ path('app_sortie_inscription',{id:sortie.id}) }}">
									<button class="btn btn-primary">S'inscrire</button>
								</a>

							{% endif %}

						{% endif %}

					</td>

				</tr>
			{% endfor %}
			</tbody>
		</table>
	</div>

{% endblock %}
{% block footer %}
	{{ parent () }}
{% endblock %}