src/Entity/HistoStories.php
<?php

namespace App\Entity;

use App\Repository\HistoStoriesRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: HistoStoriesRepository::class)]
class HistoStories
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: "integer")]
    private $id;

    #[ORM\Column(length: 50)]
    private ?string $nom_sortie = null;

    #[ORM\Column(length: 255)]
    private ?string $adresse_sortie = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_heure_debut = null;

    #[ORM\Column]
    private ?int $duree = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_limite_inscription = null;

    #[ORM\Column]
    private ?int $nb_inscriptions_max = null;

    #[ORM\Column(length: 255)]
    private ?string $infos_sortie = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $motif_annulation = null;

    #[ORM\Column(length: 10)]
    private ?string $libelle_etat = null;

    #[ORM\Column(length: 255)]
    private ?string $nom_organisateur = null;

    #[ORM\Column(length: 50)]
    private ?string $prenom_organisateur = null;

    #[ORM\Column(length: 50)]
    private ?string $tel_organisateur = null;

    #[ORM\Column(length: 50)]
    private ?string $email_organisateur = null;

    #[ORM\Column(length: 50)]
    private ?string $pseudo_organisateur = null;

    #[ORM\Column(length: 50)]
    private ?string $site_organisateur = null;

    #[ORM\Column(type: Types::JSON)]
    private array $participants = [];

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomSortie(): ?string
    {
        return $this->nom_sortie;
    }

    public function setNomSortie(string $nom_sortie): static
    {
        $this->nom_sortie = $nom_sortie;

        return $this;
    }

    public function getAdresseSortie(): ?string
    {
        return $this->adresse_sortie;
    }

    public function setAdresseSortie(string $adresse_sortie): static
    {
        $this->adresse_sortie = $adresse_sortie;

        return $this;
    }

    public function getDateHeureDebut(): ?\DateTimeInterface
    {
        return $this->date_heure_debut;
    }

    public function setDateHeureDebut(\DateTimeInterface $date_heure_debut): static
    {
        $this->date_heure_debut = $date_heure_debut;

        return $this;
    }

    public function getDuree(): ?int
    {
        return $this->duree;
    }

    public function setDuree(int $duree): static
    {
        $this->duree = $duree;

        return $this;
    }

    public function getDateLimiteInscription(): ?\DateTimeInterface
    {
        return $this->date_limite_inscription;
    }

    public function setDateLimiteInscription(\DateTimeInterface $date_limite_inscription): static
    {
        $this->date_limite_inscription = $date_limite_inscription;

        return $this;
    }

    public function getNbInscriptionsMax(): ?int
    {
        return $this->nb_inscriptions_max;
    }

    public function setNbInscriptionsMax(int $nb_inscriptions_max): static
    {
        $this->nb_inscriptions_max = $nb_inscriptions_max;

        return $this;
    }

    public function getInfosSortie(): ?string
    {
        return $this->infos_sortie;
    }

    public function setInfosSortie(string $infos_sortie): static
    {
        $this->infos_sortie = $infos_sortie;

        return $this;
    }

    public function getMotifAnnulation(): ?string
    {
        return $this->motif_annulation;
    }

    public function setMotifAnnulation(string $motif_annulation): static
    {
        $this->motif_annulation = $motif_annulation;

        return $this;
    }

    public function getLibelleEtat(): ?string
    {
        return $this->libelle_etat;
    }

    public function setLibelleEtat(string $libelle_etat): static
    {
        $this->libelle_etat = $libelle_etat;

        return $this;
    }

    public function getNomOrganisateur(): ?string
    {
        return $this->nom_organisateur;
    }

    public function setNomOrganisateur(string $nom_organisateur): static
    {
        $this->nom_organisateur = $nom_organisateur;

        return $this;
    }

    public function getPrenomOrganisateur(): ?string
    {
        return $this->prenom_organisateur;
    }

    public function setPrenomOrganisateur(string $prenom_organisateur): static
    {
        $this->prenom_organisateur = $prenom_organisateur;

        return $this;
    }

    public function getTelOrganisateur(): ?string
    {
        return $this->tel_organisateur;
    }

    public function setTelOrganisateur(string $tel_organisateur): static
    {
        $this->tel_organisateur = $tel_organisateur;

        return $this;
    }

    public function getEmailOrganisateur(): ?string
    {
        return $this->email_organisateur;
    }

    public function setEmailOrganisateur(string $email_organisateur): static
    {
        $this->email_organisateur = $email_organisateur;

        return $this;
    }

    public function getPseudoOrganisateur(): ?string
    {
        return $this->pseudo_organisateur;
    }

    public function setPseudoOrganisateur(string $pseudo_organisateur): static
    {
        $this->pseudo_organisateur = $pseudo_organisateur;

        return $this;
    }

    public function getSiteOrganisateur(): ?string
    {
        return $this->site_organisateur;
    }

    public function setSiteOrganisateur(string $site_organisateur): static
    {
        $this->site_organisateur = $site_organisateur;

        return $this;
    }

    public function getParticipants(): array
    {
        return $this->participants;
    }

    public function setParticipants(array $participants): static
    {
        $this->participants = $participants;

        return $this;
    }
}

src/Form/SortieType.php
<?php

namespace App\Form;

use App\Entity\Sortie;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Callback;
use Symfony\Component\Validator\Context\ExecutionContextInterface;
use Vich\UploaderBundle\Form\Type\VichImageType;

class SortieType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('dateDebut',\Symfony\Component\Form\Extension\Core\Type\DateTimeType::class,[
                'html5' => true,
                'date_widget' => 'single_text',
                'time_widget' => 'single_text',
                'data' => new \DateTime('tomorrow'),
                'invalid_message' => 'La date ne peut pas être dans le passé ou aujourd\'hui.',
                'constraints' => [
                    new Callback(function ($object, ExecutionContextInterface $context) {
                        if ($object < new \DateTime('today')) {
                            $context->addViolation('La date ne peut pas être dans le passé.');
                        }
                    }),
                ],

            ])
            ->add('duree')
            ->add('dateCloture', DateType::class, [
                'html5' => true,
                'widget' => 'single_text',
                'constraints' => [
                    new Callback([$this, 'validateDateCloture']),
                ],
            ])
            ->add('descriptioninfos')
            ->add('lieu', null, [
                'label' => 'Ville',
                'choice_label' => 'ville.nom'
            ])
            ->add('nbInscriptionsMax')
            ->add('imageFile', VichImageType::class, [
                'label' => 'Image',
                'help' => 'Formats autorisés (JPEG, JPG, PNG) | Poids max. (5 Mo)',
                'required' => false,
                'allow_delete' => false,
                'download_uri' => false,
                'asset_helper' => true]
            )
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Sortie::class,
        ]);
    }

    public function validateDateCloture($dateCloture, ExecutionContextInterface $context)
    {
        $dateDebut = $context->getRoot()->getData()->getDateDebut();
        $today = new \DateTime('today');

        if ($dateCloture < $today) {
            $context->buildViolation('La date de clôture ne peut pas être dans le passé.')
                ->atPath('dateCloture')
                ->addViolation();
        }

        if ($dateCloture >= $dateDebut) {
            $context->buildViolation('La date de clôture doit être antérieure à la date de début.')
                ->atPath('dateCloture')
                ->addViolation();
        }
    }
}

src/Controller/SortieController.php
<?php

namespace App\Controller;

use App\Entity\Sortie;
use App\Entity\User;
use App\Form\AnnulationType;
use App\Form\SortieType;
use App\Repository\EtatRepository;
use App\Repository\LieuRepository;
use App\Repository\SortieRepository;
use App\Repository\VilleRepository;
use App\utils\EtatEnum;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class SortieController extends AbstractController
{

    #[Route("/sortie/creer", name: "app_sortie_creer")]
    public function creerSortie(Request $request,
                                EntityManagerInterface $entityManager,
                                SortieRepository $sortieRepository,
    LieuRepository $lieuRepository): Response
    {
        $user=$this->getUser();
        $site=$user->getSite();

        $sortie = new Sortie();
        $sortie->setSite($site);
        $sortie->setEtat(EtatEnum::CREEE);
        $sortie->setAuteur($user);

        $sortieForm = $this->createForm(SortieType::class, $sortie);
        $sortieForm->handleRequest($request);

            if ($sortieForm->isSubmitted() && $sortieForm->isValid() )
            {
                $env= $request->request->get('creer');
                $publier='publier';

                if($env=== $publier) {
                    $sortie->setEtat(EtatEnum::OUVERTE);
                    $entityManager->persist($sortie);
                    $entityManager->flush();
                    $this->addFlash('success', 'Votre Sortie à été créee et publiée avec succes!');
                    return $this->redirectToRoute('app_home');
                }

            $entityManager->persist($sortie);
            $entityManager->flush();

            // do anything else you need here, like send an email
            $this->addFlash('success', 'Votre Sortie à été crée avec succes!');
            return $this->redirectToRoute('app_home');
        }

        return $this->render('sortie/creer.html.twig', [
            'sortieForm' => $sortieForm->createView()
        ]);
    }



    #[Route("/lieux-villes", name: "api_lieux_villes")]
    public function getAllVillesApi(VilleRepository $villeRepository): Response
    {
        $villes = $villeRepository->findAll();
        $response = [];

        foreach ($villes as $ville) {
            $lieux = [];
            foreach ($ville->getLieux() as $lieu) {
                $lieux[] = [
                    'id' => $lieu->getId(),
                    'nom' => $lieu->getNom(),
                ];
            }

            $response[] = [
                'ville' => [
                    'id' => $ville->getId(),
                    'nom' => $ville->getNom(),
                    'codePostal' => $ville->getCodePostal(),
                ],
                'lieux' => $lieux,
            ];
        }

        // Réponse au format JSON
        return $this->json($response, 200, [], ['groups' => 'lieu']);
    }



    #[Route("/sortie/afficher/{id<[0-9]+>}", name: "app_sortie_afficher")]
    public function afficher(Sortie $sortie): Response
    {
        return $this->render('sortie/afficher.html.twig', compact('sortie'));
    }

    #[Route("/sortie/modifier/{id<[0-9]+>}", name: "app_sortie_modifier")]
    public function modifierSortie(Request $request,EntityManagerInterface $entityManager,
                                   SortieRepository $sortieRepository,
                                   $id): Response
    {
        $user=$this->getUser();
        $sortie =$sortieRepository->find($id);

        $sortieForm = $this->createForm(SortieType::class, $sortie);
        $sortieForm->handleRequest($request);
    
        if ($sortieForm->isSubmitted() && $sortieForm->isValid()) {
            $dateDebut = $sortie->getDateDebut();
            $dateCloture = $sortie->getDateCloture();
    
            if ($dateCloture >= $dateDebut) {
                $this->addFlash('error', 'La date de clôture doit être strictement inférieure à la date de début.');
                return $this->redirectToRoute('app_sortie_modifier', ['id' => $id]);
            }
    
            $env = $request->request->get('modifier');
    
            $publier = 'publier';
            $supprimer = 'supprimer';
    
            if ($env === $publier) {
                $sortie->setEtat(EtatEnum::OUVERTE);
                $entityManager->persist($sortie);
                $entityManager->flush();
                $this->addFlash('success', 'Votre Sortie à été publiée avec succes!');
                return $this->redirectToRoute('app_home');
            } elseif ($env === $supprimer) {
                $entityManager->remove($sortie);
                $entityManager->flush();
                $this->addFlash('success', 'Votre Sortie à été supprimée avec succes!');
                return $this->redirectToRoute('app_home');
            }
    
            $entityManager->persist($sortie);
            $entityManager->flush();
    
            $this->addFlash('success', 'Votre Sortie à été modifié avec succes!');
            return $this->redirectToRoute('app_home');
        }
    
        return $this->render('sortie/modifier.html.twig', [
            'sortieForm' => $sortieForm->createView(),
            'sortie' => $sortie
        ]);
    }
    

    #[Route("/sortie/inscription/{id<[0-9]+>}", name: "app_sortie_inscription")]
    public function inscription (SortieRepository $sortieRepository,$id,
                                 EntityManagerInterface $entityManager): Response
    {
        $user=$this->getUser();
        $sortie =$sortieRepository->find($id);
        $sortie->addUsersInscrit($user);

        if ($sortie->getNbInscriptionsMax() === $sortie->getUsersInscrits()->count()) {
            $sortie->setEtat(EtatEnum::CLOTUREE);
        }
        $entityManager->persist($sortie);
        $entityManager->flush();
        $this->addFlash('success', 'Vous vous etes inscrit avec succés!');
        return $this->redirectToRoute('app_home');
    }


    #[Route("/sortie/publication/{id<[0-9]+>}", name: "app_sortie_publication")]
    public function publication (SortieRepository $sortieRepository,
                                 $id,
                                 EntityManagerInterface $entityManager): Response
    {

        $sortie = $sortieRepository->find($id);
        $sortie->setEtat(EtatEnum::OUVERTE);
        $entityManager->flush();
        $this->addFlash('success', 'Votre sortie à été publiée avec succès!');
        return $this->redirectToRoute('app_home');
    }

    #[Route("/sortie/desister/{id<[0-9]+>}", name: "app_sortie_desister")]
    public function desister (SortieRepository $sortieRepository,$id,EntityManagerInterface $entityManager): Response
    {
        $user = $this->getUser();
        $sortie = $sortieRepository->find($id);
        $sortie->removeUsersInscrit($user);

        if ($sortie->getNbInscriptionsMax() > $sortie->getUsersInscrits()->count()) {
            $sortie->setEtat(EtatEnum::OUVERTE);
        }
        $entityManager->persist($sortie);
        $entityManager->flush();
        $this->addFlash('success', 'Vous vous êtes désisté avec succès!');
        return $this->redirectToRoute('app_home');
    }

    #[Route("/annuler/sortie/{id<[0-9]+>}", name: "app_sortie_annuler")]
    public function annulerSortie(Request $request,
                                  EntityManagerInterface $entityManager,
                                  SortieRepository $sortieRepository,
    $id): Response
    {
        $sortie =$sortieRepository->find($id);

        $annulerSortieForm = $this->createForm(AnnulationType::class, $sortie);
        $annulerSortieForm->handleRequest($request);

        if ($annulerSortieForm->isSubmitted() && $annulerSortieForm->isValid()) {
            $env = $request->request->get('annuler');
            $annuler = 'annuler';
            $enregistrer = 'enregistrer';

            if ($env == $annuler) {
                return $this->redirectToRoute('app_home');
                // do anything else you need here, like send an email
            }

            $sortie->setEtat(EtatEnum::ANNULEE);
            $entityManager->persist($sortie);
            $entityManager->flush();

            // do anything else you need here, like send an email
            $this->addFlash('success', 'Votre Sortie a été annulée avec succès!');
            return $this->redirectToRoute('app_home');
        }

        return $this->render('sortie/annulerSortie.html.twig', [
            'annulerSortieForm' => $annulerSortieForm->createView(), 'sortie' => $sortie
        ]);
    }
}

templates/sortie/afficher.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <section class="vh-100" style="background-color: #9A616D;">
        <div class="container py-5 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col col-xl-10">
                    <div class="card" style="border-radius: 1rem;">
                        <div class="row g-0">
                            <div class="col-md-6 col-lg-5 d-none d-md-block">
                                {% if sortie.imageName %}
                                <img src="{{ asset('uploads/sortie/' ~ sortie.imageName) }}"
                                     alt="{{ sortie.nom }}" class="img-fluid" style="border-radius: 1rem 0 0 1rem;" />
                                {% else %}
                                    <img src="{{ asset('img/default_sortie.png') }}" alt="sortie"  class="img-fluid" style="border-radius: 1rem 0 0 1rem;">
                                {% endif %}
                            </div>
                            <div class="col-md-6 col-lg-7 d-flex align-items-center">
                                <div class="card-body p-4 p-lg-5 text-black">


                                    <div class="d-flex align-items-center mb-3 pb-1">

                                        <i class="fas fa-cubes fa-2x me-3" style="color: #ff6219;"></i>
                                        <a href="{{ path('app_login') }}"><img src="{{ asset('img/Logo.svg') }} "width="200" alt="sortir.com"></a>
                                        <span hidden class="h2 fw-bold mb-0">{{ sortie.nom }}</span>
                                    </div>
                                    {% if sortie.etat =='Annulée' %}
                                    <div>
                                       <p class="text-danger"> <b>Motif d'annulation :</b> {{ sortie.motifAnnulation }}</p>
                                    </div>
                                    {% endif %}

                                    <div>
                                        <p>Nom : <b>{{ sortie.nom}}</b></p>
                                    </div>

                                    <div>
                                        <p>Date et heure de la sortie : <b>{{ sortie.dateDebut | date('d/m/Y H:i')}}</b></p>
                                    </div>


                                    <div>
                                        <p>Date limite d'inscription : <b>{{ sortie.dateCloture | date('d/m/Y')}}</b></p>
                                    </div>


                                    <div>
                                        <p>Nombre de places : <b>{{ sortie.nbInscriptionsMax }}</b></p>
                                    </div>


                                    <div>
                                        <p>Durée : <b>{{ sortie.duree}}</b></p>
                                    </div>


                                    <div>
                                        <p>Description et infos : <b>{{ sortie.descriptioninfos}}</b></p>
                                    </div>

                                    <div>
                                        <p>Ville organisatrice : <b>{{app.user.site ? app.user.site.nom : '' }}</b></p>
                                    </div>


                                    <div>
                                        <p>Lieu : <b>{{ sortie.lieu.nom}}</b></p>
                                    </div>

                                    <div>
                                        <p>Rue : <b>{{ sortie.lieu.rue}}</b></p>
                                    </div>
                                    <div>
                                        <p>Code postal : <b>{{ sortie.lieu.ville.codePostal}}</b></p>
                                    </div>
                                        {% if sortie.lieu.latitude  %}
                                    <div>
                                        <p>Latitude : <b>{{ sortie.lieu.latitude}}</b></p>
                                    </div>
                                        {% endif %}

                                    {% if sortie.lieu.longitude  %}
                                    <div>
                                        <p>Longitude: <b>{{ sortie.lieu.longitude}}</b></p>
                                    </div>
                                    {% endif %}

                                    <div>
                                        <h4>Liste des participants inscrits : </h4>
                                        <table class="table">
                                            <thead>
                                            <tr>
                                                <th scope="col">#</th>
                                                <th scope="col">Pseudo</th>
                                                <th scope="col">Nom</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            {%  for u in sortie.usersInscrits %}
                                            <tr>
                                                <th scope="row"></th>

                                                <td>{% if sortie.auteur ==   app.user or u == app.user or 'ROLE_ADMIN' in app.user.roles%}
                                                    <a href="{{ path('app_user_afficher',{id:u.id}) }}">{{ u.pseudo |upper }}</a>
                                                        {% else %}
                                                           {{ u.pseudo |upper }}
                                                    {% endif %}

                                                </td>

                                                <td>{{ u.nom |capitalize}}   {{ u.prenom}}</td>
                                            </tr>
                                            {% endfor%}

                                            </tbody>
                                        </table>

                                    </div>
                                    <a href="{{ path('app_home') }}"><button type="submit" class="btn btn-dark">Retour</button></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>


{% endblock %}

{% block title %}

{% endblock %}

templates/sortie/annulerSortie.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {{ parent() }}
<section class="vh-100" style="background-color: #9A616D;">
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col col-xl-10">
                <div class="card" style="border-radius: 1rem;">
                    <div class="row g-0">
                        <div class="col-md-6 col-lg-7 d-flex align-items-center">
                            <div class="card-body p-4 p-lg-5 text-black">

                                <div class="d-flex align-items-center mb-3 pb-1">

                                    <i class="fas fa-cubes fa-2x me-3" style="color: #ff6219;"></i>
                                    <a href="{{ path('app_login') }}"><img src="{{ asset('img/Logo.svg') }} "width="200" alt="sortir.com"></a>
                                    <span class="h2 fw-bold mb-0">Créer une sortie</span>
                                </div>
                                <div>
                                    <h1 class="text-center">Annuler une sortie </h1>
                                </div>


                                <div>
                                    <p>Nom : <b>{{ sortie.nom }}</b></p>
                                </div>


                                <div>
                                    <p>Date de début : <b>{{ sortie.dateDebut | date('d/m/Y')}} </b></p>
                                </div>


                                <div>
                                    <p>Campus : <b>{{ sortie.auteur.site.nom }}</b></p>
                                </div>


                                <div>
                                    <p>Lieu : <b>{{ sortie.lieu.rue }} {{ sortie.lieu.ville.codePostal }}-{{ sortie.lieu.nom }}</b></p>
                                </div>

                                {{ form_start(annulerSortieForm) }}
                                {{ form_row(annulerSortieForm.motifAnnulation,{
                                    attr:{
                                        class:'form-control '
                                    },row_attr:{
                                        class:'form-group'
                                    }
                                }) }}

                                <button type="submit" class="btn btn-dark" name="annuler" value="enregistrer">Enregistrer</button>
                                <button type="submit" class="btn btn-danger" name="annuler" value="annuler">Annuler</button>



                                {{ form_end(annulerSortieForm) }}







                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


{% endblock %}

{% block title %}

{% endblock %}